//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hairdresser_Salon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezerwacje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rezerwacje()
        {
            this.Uzytkownicy = new HashSet<Uzytkownicy>();
        }
    
        public int IDRezerwacji { get; set; }
        public Nullable<int> IDZakladu { get; set; }
        public Nullable<int> IDUslugi { get; set; }
        public string NumerRezerwacji { get; set; }
        public System.DateTime DataIGodzinaRezerwacji { get; set; }
    
        public virtual Uslugi Uslugi { get; set; }
        public virtual ZakladyFryzjerskie ZakladyFryzjerskie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uzytkownicy> Uzytkownicy { get; set; }
    }
}
